# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vdss_types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vdss_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10vdss_types.proto\x12\x04vdss\"0\n\x10VectorIdentifier\x12\x0e\n\x06u64_id\x18\x01 \x01(\x04\x12\x0c\n\x04uuid\x18\x02 \x01(\t\")\n\x06Vector\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\x11\n\tdimension\x18\x02 \x01(\r\"\x17\n\x07Payload\x12\x0c\n\x04json\x18\x01 \x01(\t\"@\n\nHnswConfig\x12\t\n\x01m\x18\x01 \x01(\r\x12\x14\n\x0c\x65\x66_construct\x18\x02 \x01(\r\x12\x11\n\tef_search\x18\x03 \x01(\r\"\x91\x02\n\x10\x43ollectionConfig\x12\'\n\x0cindex_driver\x18\x01 \x01(\x0e\x32\x11.vdss.IndexDriver\x12-\n\x0findex_algorithm\x18\x02 \x01(\x0e\x32\x14.vdss.IndexAlgorithm\x12\'\n\x0cstorage_type\x18\x03 \x01(\x0e\x32\x11.vdss.StorageType\x12\x11\n\tdimension\x18\x04 \x01(\r\x12-\n\x0f\x64istance_metric\x18\x05 \x01(\x0e\x32\x14.vdss.DistanceMetric\x12\x13\n\x0b\x63onfig_json\x18\x06 \x01(\t\x12%\n\x0bhnsw_config\x18\x07 \x01(\x0b\x32\x10.vdss.HnswConfig\"\x7f\n\x0cSearchResult\x12\"\n\x02id\x18\x01 \x01(\x0b\x32\x16.vdss.VectorIdentifier\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x1c\n\x06vector\x18\x03 \x01(\x0b\x32\x0c.vdss.Vector\x12\x1e\n\x07payload\x18\x04 \x01(\x0b\x32\r.vdss.Payload\"\x8d\x01\n\x0f\x43ollectionStats\x12\x15\n\rtotal_vectors\x18\x01 \x01(\x04\x12\x17\n\x0findexed_vectors\x18\x02 \x01(\x04\x12\x17\n\x0f\x64\x65leted_vectors\x18\x03 \x01(\x04\x12\x15\n\rstorage_bytes\x18\x04 \x01(\x04\x12\x1a\n\x12index_memory_bytes\x18\x05 \x01(\x04\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t*\x1a\n\x0eIndexAlgorithm\x12\x08\n\x04HNSW\x10\x00*\x18\n\x0bIndexDriver\x12\t\n\x05\x46\x41ISS\x10\x00*;\n\x0bStorageType\x12\x10\n\x0c\x42TRIEVE_FILE\x10\x00\x12\x07\n\x03MEM\x10\x01\x12\x11\n\rBTRIEVE_SPACE\x10\x02*4\n\x0e\x44istanceMetric\x12\n\n\x06\x43OSINE\x10\x00\x12\r\n\tEUCLIDEAN\x10\x01\x12\x07\n\x03\x44OT\x10\x02*7\n\x0f\x43ollectionState\x12\t\n\x05READY\x10\x00\x12\x0e\n\nREBUILDING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vdss_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INDEXALGORITHM']._serialized_start=800
  _globals['_INDEXALGORITHM']._serialized_end=826
  _globals['_INDEXDRIVER']._serialized_start=828
  _globals['_INDEXDRIVER']._serialized_end=852
  _globals['_STORAGETYPE']._serialized_start=854
  _globals['_STORAGETYPE']._serialized_end=913
  _globals['_DISTANCEMETRIC']._serialized_start=915
  _globals['_DISTANCEMETRIC']._serialized_end=967
  _globals['_COLLECTIONSTATE']._serialized_start=969
  _globals['_COLLECTIONSTATE']._serialized_end=1024
  _globals['_VECTORIDENTIFIER']._serialized_start=26
  _globals['_VECTORIDENTIFIER']._serialized_end=74
  _globals['_VECTOR']._serialized_start=76
  _globals['_VECTOR']._serialized_end=117
  _globals['_PAYLOAD']._serialized_start=119
  _globals['_PAYLOAD']._serialized_end=142
  _globals['_HNSWCONFIG']._serialized_start=144
  _globals['_HNSWCONFIG']._serialized_end=208
  _globals['_COLLECTIONCONFIG']._serialized_start=211
  _globals['_COLLECTIONCONFIG']._serialized_end=484
  _globals['_SEARCHRESULT']._serialized_start=486
  _globals['_SEARCHRESULT']._serialized_end=613
  _globals['_COLLECTIONSTATS']._serialized_start=616
  _globals['_COLLECTIONSTATS']._serialized_end=757
  _globals['_STATUS']._serialized_start=759
  _globals['_STATUS']._serialized_end=798
# @@protoc_insertion_point(module_scope)
